config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'memes#index'

  get 'memes/filter/:filter' => 'memes#index', as: :filtered_memes

  resources :memes do
    resources :reviews
    resources :likes, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy] 

  resources :users do
    get 'edit/:page' => 'users#edit', as: :resource_pages
  end
  get 'signup' => 'users#new'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :memes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_memes, through: :likes, source: :meme

  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false }

  AVATAR_OPTIONS = ["avatar1.png", "avatar2.png", "avatar3.png", "avatar4.png", "avatar5.png"]

  validates :profile_image, inclusion: { in: AVATAR_OPTIONS }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: %i[new create]
  before_action :require_admin, only: [:index]
  before_action :require_correct_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user), notice: 'User successfully created'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update_attributes(user_params)
      redirect_to edit_user_path, notice: 'User was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    redirect_to signup_path, alert: 'Account was successfully deleted'
  end

  private

  def require_correct_user
    @user = User.find(params[:id] || params[:user_id])
    redirect_to root_path, alert: 'Unauthorized access!' unless current_user?(@user)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def pro_or_memeber(user)
    user.admin_status ? 'PRO' : 'MEMEBER'
  end

  def which_page
    case params[:page]
    when 'reviews'
      'reviews'
    when 'memes'
      'memes'
    when 'likes'
      'likes'
    else
      'profile'
    end
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |u| %>
    <div class="content-panel">
        <% if user.new_record? %>
            <h2 class="title">Sign Up</h2>
            <h4 class="center">Become a member to upload your own memes and review them!</h4>
        <% else %>
            <h2 class="title">Profile <span class="pro-label label label-warning">
            <% if user.admin_status == true %>
                PRO
            <% else %>
                MEMEBER
            <% end %>
            </span></h2>
        <% end %>
        <form class="form-horizontal">

            <fieldset class="fieldset">
                <h3 class="fieldset-title">Avatar</h3>
                <div>
                    <%= u.label :profile_image, class: "control-label" %>
                    <%= u.select :profile_image, User::AVATAR_OPTIONS,
                        prompt: "Pick an avatar" %>
                </div>
            </fieldset>
            <fieldset>
                <h3 class="fieldset-title">Profile info</h3>
                <div class="form-group">
                    <%= u.label :name %>
                    <%= u.text_field :name, {class: "form-control"} %>
                </div>

                <div class="form-group">
                    <%= u.label :email %>
                    <%= u.text_field :email, {class: "form-control"}%>
                </div>

                <div class="form-group">
                    <%= u.label :password %>
                    <%= u.password_field :password, {class: "form-control"} %>
                </div>
                <div class="form-group">
                    <%= u.label :password_confirmation, "Confirm Password" %>
                    <%= u.password_field :password_confirmation, {class: "form-control"} %>
                </div>
            </fieldset>
            <hr>
            <div class="form-group">
                <div class="btn-bar">
                    <% if user.new_record? %>
                        <%= u.submit "Create Account", {class: "btn btn-primary"} %>
                        <%= link_to "Cancel", root_path, class: "btn btn-primary" %>
                    <% else %>
                        <%= u.submit "Update Account", {class: "btn btn-primary"} %>
                        <%= link_to "Delete", @event, method: :delete, 
                            data: { confirm: "Are you sure you want to delete this user?" }, class: "btn btn-primary" 
                        %>
                    <% end %>
                </div>
            </div>
        </form>
    </div>
<% end %>  

app/views/users/_likes.html.erb
<div class="content-panel">
    <h2 class="title">Liked Memes <span class="pro-label label label-warning">
    <% if user.admin_status == true %>
        PRO
    <% else %>
        MEMEBER
    <% end %>
    </span></h2>
    <fieldset class="fieldset">
        <h3 class="fieldset-title"><%= pluralize(user.liked_memes.size, 'Like')%></h3>
    </fieldset>
    <% user.liked_memes.each do |meme| %>
        <fieldset class="fieldset">
            <div class="blog-grid">
                <div class="blog-img">
                    <div class="date"><%= day_month(meme) %></div>
                    <a href=<%= meme_path(meme) %>>
                    <%= meme_image(meme, 'height:320px;width:320px;') %>
                    </a>
                </div>
                <div class="blog-info">
                    <h5><a href=<%= meme_path(meme) %>><%= meme.name %></a></h5>
                    <p><%= truncate(meme.description, length: 90, separator: '') %></p>
                    <div class="btn-bar">
                    <a href=<%= meme_path(meme) %> class="px-btn-arrow">
                        <span>Learn More</span>
                        <i class="arrow"></i>
                    </a>
                    </div>
                </div>
            </div>
        </fieldset>
    <% end %>
</div>

app/views/users/_memes.html.erb
<div class="content-panel">
    <h2 class="title">Uploaded Memes <span class="pro-label label label-warning">
    <% if user.admin_status == true %>
        PRO
    <% else %>
        MEMEBER
    <% end %>
    </span></h2>
    <fieldset class="fieldset">
        <h3 class="fieldset-title"><%= pluralize(user.memes.size, 'Meme') %></h3>
    </fieldset>
    <% user.memes.each do |meme| %>
        <fieldset class="fieldset">
            <div class="blog-grid">
                <div class="blog-img">
                    <div class="date"><%= day_month(meme) %></div>
                    <a href=<%= meme_path(meme) %>>
                    <%= meme_image(meme, 'height:320px;width:320px;') %>
                    </a>
                </div>
                <div class="blog-info">
                    <h5><a href=<%= meme_path(meme) %>><%= meme.name %></a></h5>
                    <p><%= truncate(meme.description, length: 90, separator: '') %></p>
                    <div class="btn-bar">
                        <span><%= link_to "Edit", edit_meme_path(meme), class: "px-btn-arrow" %></span>
                    </div>
                </div>
            </div>
        </fieldset>
    <% end %>
</div>

app/views/users/_reviews.html.erb
<div class="content-panel">
    <h2 class="title">Reviews <span class="pro-label label label-warning">
    <% if user.admin_status == true %>
        PRO
    <% else %>
        MEMEBER
    <% end %>
    </span></h2>
    <fieldset class="fieldset">
        <h3 class="fieldset-title"><%= pluralize(user.reviews.size, 'Review') %></h3>
    </fieldset>
    <% user.reviews.each do |r| %>
        <fieldset class="fieldset" style="padding-top: 10px">
            <div class="blog-grid">
                <div class="blog-info">
                    <% r.stars.to_i.times do %>
                        <span class="fa fa-star checked"></span>
                    <% end %>
                    <% (5 - r.stars.to_i).times do %>
                        <span class="fa fa-star"></span>
                    <% end %>
                    <h4>For <%= link_to r.meme.name, meme_path(r.meme) %></h4>
                    <p><%= r.review %></p>
                    <small><%= day_month(r) %></small>
                    <%= link_to "Edit", edit_meme_review_path(r.meme.slug, r), class: "px-btn-arrow" %>
                </div>
            </div>
        </fieldset>
    <% end %>
</div>

app/views/users/edit.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <%= render "shared/errors", object: @user %>
    <div class="view-account">
        <section class="module">
            <div class="module-inner">
                <div class="side-bar">
                    <div class="user-info">
                        <%= image_tag @user.profile_image, class: "img-profile img-circle img-responsive center-block" %>
                        <ul class="meta list list-unstyled">
                            <li class="name"><%= @user.name.capitalize %>
                                <label class="label label-info"><%= pro_or_memeber(@user) %></label>
                            </li>
                            <li class="email"><%= mail_to(@user.email) %></li>
                            <li class="activity">Memeber since: <%= time_ago_in_words(@user.created_at) %> ago</li>
                        </ul>
                    </div>
            		<nav class="side-menu">
        				<ul class="nav">
                            <li class="<%= 'active' if which_page == 'profile' %>"><%= link_to edit_user_path(@user) do %>
                                <span class="fa fa-user"></span> Profile
                            <% end %></li>
                            <li class="<%= 'active' if which_page == 'memes' %>"><%= link_to user_resource_pages_path(@user, 'memes') do %>
                                <span class="fa fa-th"></span> Memes
                            <% end %></li>
                            <li class="<%= 'active' if which_page == 'reviews' %>"><%= link_to user_resource_pages_path(@user, 'reviews') do %>
                                <span class="fa fa-star-half-o" aria-hidden="true"></span> Reviews
                            <% end %></li>
                            <li class="<%= 'active' if which_page == 'likes' %>"><%= link_to user_resource_pages_path(@user, 'likes') do %>
                                <span class="fa fa-thumbs-o-up" aria-hidden="true"></span> Likes
                            <% end %></li>
        				</ul>
        			</nav>
                </div>
                <% if which_page == 'reviews' %>
                    <%= render 'reviews', user: @user %>
                <% elsif which_page == 'memes' %>
                    <%= render 'memes', user: @user %>
                <% elsif which_page == 'likes' %>
                    <%= render 'likes', user: @user %>
                <% else %>
                    <%= render 'form', user: @user %>
                <% end %>
            </div>
        </section>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <ul>
        <section>
            <h2><%= pluralize(@users.size, "User") %></h2>
            <% @users.each do |u| %>
                <li>
                    <%= link_to u.name, u %>
                    created
                    <%= time_ago_in_words(u.created_at) %> ago
                <li>
            <% end %>
        </section>
    </ul>
</div>

app/views/users/new.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <%= render "shared/errors", object: @user %>
    <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="about-text">
        <h3><%= @user.name %></h1>
        <h4><%= mail_to(@user.email) %></h2>
        <% if current_user?(@user) %>
            <div class="btn-bar">
                <%= link_to "Edit User", edit_user_path, class: "btn btn-primary" %>
                <%= link_to "Delete", @event, method: :delete, 
                    data: { confirm: "Are you sure you want to delete this user?" }, class: "btn btn-primary" 
                %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/userreviews.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <%= render "shared/errors", object: @user %>
    <div class="view-account">
        <section class="module">
            <div class="module-inner">
                <div class="side-bar">
                    <div class="user-info">
                        <%= image_tag @user.profile_image, class: "img-profile img-circle img-responsive center-block" %>
                        <ul class="meta list list-unstyled">
                            <li class="name"><%= @user.name.capitalize %>
                                <label class="label label-info"><%= pro_or_memeber(@user) %></label>
                            </li>
                            <li class="email"><%= mail_to(@user.email) %></li>
                            <li class="activity">Memeber since: <%= time_ago_in_words(@user.created_at) %> ago</li>
                        </ul>
                    </div>
            		<nav class="side-menu">
        				<ul class="nav">
        					<li class="active"><a href="#"><span class="fa fa-user"></span> Profile</a></li>
        					<li><a href="#"><span class="fa fa-envelope"></span> Reviews</a></li>
        					<li><a href="user-drive.html"><span class="fa fa-th"></span> Memes</a></li>
        				</ul>
        			</nav>
                </div>

                <%= render 'form', user: @user %>
            </div>
        </section>
    </div>
</div>