config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'memes#index'

  get 'memes/filter/:filter' => 'memes#index', as: :filtered_memes

  resources :memes do
    resources :reviews
    resources :likes, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy] 

  resources :users do
    get 'edit/:page' => 'users#edit', as: :resource_pages
  end
  get 'signup' => 'users#new'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_meme_or_user
  before_action :require_signin
  before_action :require_correct_user_or_admin, only: %i[edit update destroy]

  def index
    @reviews = @object.reviews
  end

  def edit
    @review = @object.reviews.find(params[:id])
  end

  def update
    @review = @object.reviews.find(params[:id])
    if @review.update(review_params)
      redirect_to meme_reviews_path(@object), notice: 'Review updated successfuly'
    else
      render :edit
    end
  end

  def new
    @review = @object.reviews.new
  end

  def create
    @review = @object.reviews.new(review_params)

    if @review.save
      redirect_to meme_reviews_path(@object), notice: 'Review submitted'
    else
      render :new
    end
  end

  private

  def require_correct_user_or_admin
    @review = @object.reviews.find(params[:id])
    if params[:user_id]
      current_user
      redirect_to root_path unless current_user?(@user)
    else
      current_user
      redirect_to root_path unless current_user.admin_status == true || current_user.id == @review.user_id
    end
  end

  def review_params
    defaults = {user_id: current_user.id }
    params.require(:review).permit(:review, :stars, :user_id).reverse_merge!(defaults)
  end

  def set_meme_or_user
    @object = if params[:meme_id].nil?
                User.find(params[:user_id])
              else
                Meme.find_by!(slug: params[:meme_id])
              end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def day_month(review)
    review.blank? ? 'no date' : review.updated_at.strftime('%d %b %Y')
  end

  def get_meme(object, review)
    if object.class != Meme
      return Meme.find(review.meme_id)
    else
      return object
    end
  end

  def get_user(review)
    User.find(review.user_id)
  end

  def checked_stars(meme)
    if meme.reviews.size.zero?
      0
    else
      avg_stars(meme).to_i
    end
  end

  def unchecked_stars(meme)
    if meme.reviews.size.zero?
      0
    else
      5 - avg_stars(meme).to_i
    end
  end

  def user_not_reviewed?(meme)
    if current_user.reviews.where(meme_id: meme.id).present?
      false
    else
      true
    end
  end
end

app/views/reviews/_form.html.erb
<%= form_with(model: [@object, @review], local: true) do |r| %>
    <div class="content-panel">
        <form class="form-horizontal">
            
            <fieldset class="fieldset">
                <h3 class="fieldset-title">Meme info</h3>
                <%= render "shared/errors", object: @review %>
                
                <div class="form-group">
                    <%= r.label "Name", class: "control-label" %>
                    <%= r.text_field "Name", value: current_user.name, class: "form-control", disabled: true %>
                </div>

                <div class="form-group">
                    <%= r.label "Email", class: "control-label" %>
                    <%= r.email_field "Email", value: current_user.email, class: "form-control", disabled: true %>
                </div>

                <div class="form-group">
                    <%= r.label :review, class: "control-label" %>
                    <%= r.text_field :review, {class: "form-control"}%>
                </div>

                <div class="form-group">
                    <%= r.label :stars, class: "control-label" %>
                    <%= r.select :stars, [1, 2, 3, 4, 5], prompt: "Pick a number" %>
                </div>
            </fieldset>
            
            <hr>
            <div class="form-group">
                <%= r.submit "Submit", {class: "btn btn-primary"} %>
                <%= link_to "Discard Changes", :back || meme_reviews_path(@object), class: "btn btn-primary" %>
            </div>
        </form>
    </div>
<% end %>

app/views/reviews/edit.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <%= render "form", {meme: @meme, review: @review} %>
</div>

app/views/reviews/index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <div class="row text-center">
        <h2>Reviews from <%= @object.name %></h2>
    </div>
    <div class="row">
        
        <% @reviews.each do |r| %>
            <fieldset class="fieldset" style="padding-top: 10px">
                <div class="blog-grid">
                    <div class="blog-info">
                        <% r.stars.to_i.times do %>
                            <span class="fa fa-star checked"></span>
                        <% end %>
                        <% (5 - r.stars.to_i).times do %>
                            <span class="fa fa-star"></span>
                        <% end %>
                        <h4>From <%= r.user.name %></h4>
                        <p><%= r.review %></p>
                        <small><%= day_month(r) %></small>
                        <% if current_user?(r.user) %>
                            <% if @object.class == Meme %>
                                <%= link_to "Edit", edit_meme_review_path(r.meme, r), class: "px-btn-arrow" %>
                            <% else %>
                                <%= link_to "Edit", edit_user_review_path(r.user, r), class: "px-btn-arrow" %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </fieldset>
        <% end %>
    </div>
    <div class="row text-center">
    <% if @object.class == Review %>
        <%= link_to "Add a Review", new_meme_review_path, class: "px-btn-arrow" %>
    <% end %>
    </div>
</div>

app/views/reviews/new.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <%= render "form", {meme: @meme, review: @review} %>
</div>