config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'memes#index'

  get 'memes/filter/:filter' => 'memes#index', as: :filtered_memes

  resources :memes do
    resources :reviews
    resources :likes, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy] 

  resources :users do
    get 'edit/:page' => 'users#edit', as: :resource_pages
  end
  get 'signup' => 'users#new'
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class="success">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="warning">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Ruby Memes App
    </small>

    <nav>
        <ul>
            <p>Made by <a href="https://github.com/nullbr/rubymemeapp">Bruno Leite</p>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to image_tag("rubylogo.png", size: "80x80"), root_path, id: "logo" %> <%= link_to "Ruby Memes", root_path, id: "logotxt" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Memes</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Latest", memes_path %></li>
                        <li><%= link_to "Oldest", filtered_memes_path('oldest') %></li>
                        <li><%= link_to "Image", filtered_memes_path('png_or_jpg') %></li>
                        <li><%= link_to "Gif", filtered_memes_path('gif') %></li>
                    </ul>
                </li>
                <% if current_user %>
                    <li class="dropdown">
                        <a href=<%= edit_user_path(session[:user_id]) %> class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label"><%= current_user.name%></span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", edit_user_path(session[:user_id]) %></li>
                            <li><%= link_to "Uploaded Memes", user_resource_pages_path(current_user, 'memes') %></li>
                            <li><%= link_to "Reviews", user_resource_pages_path(current_user, 'reviews') %></li>
                            <li><%= link_to "Likes", user_resource_pages_path(current_user, 'likes') %></li>
                        </ul>
                    </li>
                    <li><%= link_to "Sign Out", session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Sign Up", signup_path %></li>
                    <li><%= link_to "Login", new_session_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
    <script src='https://code.jquery.com/jquery-2.1.3.min.js'></script>
    <script src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'></script>
    <script>
    $(function () {
        $('.dropdown-toggle').dropdown();
    }); 
    </script>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubygemapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <section class="section about-section gray-bg">
      <%= render 'layouts/flash'%>
      <%= yield %>
    </section>

    <%= render 'layouts/footer' %>
  </body>
</html>